-- A small made-up catalog to work with.
INSERT INTO titles (name, genres, release_year, duration_minutes, description) VALUES
('The Distant Circuit', ARRAY['horror','drama','comedy'], 2001, 117, 'A house that remembers everyone who left.'),
('The Glass Signal', ARRAY['drama','comedy'], 2022, 128, 'A family is pulled apart by a secret.'),
('The Last Archive', ARRAY['crime'], 2022, 22, 'A heist goes wrong in the first minute.'),
('The Glass Frontier', ARRAY['horror','family'], 1998, 128, 'A house that remembers everyone who left.'),
('The Crimson Archive', ARRAY['crime'], 2003, 104, 'A heist goes wrong in the first minute.'),
('The Hollow Circuit', ARRAY['fantasy'], 2014, 88, 'A reluctant heir inherits a haunted crown.'),
('The Hidden Island', ARRAY['romance','comedy'], 1999, 22, 'Two people keep missing each other.'),
('The Northern Tide', ARRAY['horror','crime','action'], 2015, 141, 'A house that remembers everyone who left.'),
('The Glass Station', ARRAY['documentary','sci-fi'], 2006, 95, 'A true story told by the people who lived it.'),
('The Last Island', ARRAY['crime','animation'], 2016, 141, 'A heist goes wrong in the first minute.'),
('The Wild Letter', ARRAY['comedy'], 2021, 88, 'Two strangers stumble into a scheme.'),
('The Quiet Empire', ARRAY['horror'], 1999, 117, 'A house that remembers everyone who left.'),
('The Distant Machine', ARRAY['fantasy','animation','comedy'], 2000, 104, 'A reluctant heir inherits a haunted crown.'),
('The Quiet Orchard', ARRAY['family'], 2014, 141, 'Siblings spend one strange summer together.'),
('The Wild River', ARRAY['drama','animation'], 2017, 88, 'A family is pulled apart by a secret.'),
('The Northern Frontier', ARRAY['drama','sci-fi','documentary'], 2003, 95, 'A family is pulled apart by a secret.'),
('The Burning River', ARRAY['comedy','thriller','animation'], 2020, 104, 'Two strangers stumble into a scheme.'),
('The Broken Empire', ARRAY['family','action'], 2017, 128, 'Siblings spend one strange summer together.'),
('The Midnight Circuit', ARRAY['thriller'], 2004, 95, 'A detective races a deadline.'),
('The Midnight Harbor', ARRAY['fantasy','thriller','documentary'], 2013, 22, 'A reluctant heir inherits a haunted crown.'),
('The Paper Machine', ARRAY['thriller','crime'], 1998, 141, 'A detective races a deadline.'),
('The Paper River', ARRAY['action','family','comedy'], 2025, 128, 'A retired agent takes one last job.'),
('The Crimson Tide', ARRAY['sci-fi'], 2023, 88, 'A crew finds a signal from the future.'),
('The Hidden Garden', ARRAY['comedy'], 1995, 88, 'Two strangers stumble into a scheme.'),
('The Paper Frontier', ARRAY['fantasy','drama'], 1999, 95, 'A reluctant heir inherits a haunted crown.'),
('The Northern River', ARRAY['horror','documentary'], 2017, 117, 'A house that remembers everyone who left.'),
('The Quiet Frontier', ARRAY['animation'], 2024, 141, 'A small robot looks for its way home.'),
('The Quiet Voyage', ARRAY['thriller'], 2001, 117, 'A detective races a deadline.'),
('The Frozen Echo', ARRAY['crime','drama'], 2008, 117, 'A heist goes wrong in the first minute.'),
('The Broken Code', ARRAY['crime'], 2014, 45, 'A heist goes wrong in the first minute.'),
('The Frozen Summit', ARRAY['thriller','romance'], 2009, 117, 'A detective races a deadline.'),
('The Midnight Letter', ARRAY['sci-fi','action'], 2009, 95, 'A crew finds a signal from the future.'),
('The Iron Echo', ARRAY['family','drama'], 1996, 104, 'Siblings spend one strange summer together.'),
('The Quiet Lantern', ARRAY['family','fantasy'], 2017, 141, 'Siblings spend one strange summer together.'),
('The Lost Machine', ARRAY['sci-fi'], 2001, 95, 'A crew finds a signal from the future.'),
('The Quiet Tide', ARRAY['sci-fi','animation'], 1995, 141, 'A crew finds a signal from the future.'),
('The Lost Orchard', ARRAY['action'], 2007, 141, 'A retired agent takes one last job.'),
('The Golden Empire', ARRAY['comedy','action'], 2024, 128, 'Two strangers stumble into a scheme.'),
('The Last Kingdom', ARRAY['thriller','drama'], 2004, 141, 'A detective races a deadline.'),
('The Broken Letter', ARRAY['horror','romance','thriller'], 2003, 22, 'A house that remembers everyone who left.'),
('The Silent Frontier', ARRAY['action','sci-fi'], 2008, 22, 'A retired agent takes one last job.'),
('The Frozen Tide', ARRAY['crime','sci-fi'], 2015, 104, 'A heist goes wrong in the first minute.'),
('The Paper Empire', ARRAY['drama','romance'], 2024, 128, 'A family is pulled apart by a secret.'),
('The Iron Circuit', ARRAY['crime','family'], 1996, 141, 'A heist goes wrong in the first minute.'),
('The Golden Letter', ARRAY['thriller'], 2006, 88, 'A detective races a deadline.'),
('The Quiet Letter', ARRAY['crime'], 1998, 117, 'A heist goes wrong in the first minute.'),
('The Iron Summit', ARRAY['comedy','crime','drama'], 2010, 95, 'Two strangers stumble into a scheme.'),
('The Frozen Signal', ARRAY['crime'], 2023, 22, 'A heist goes wrong in the first minute.'),
('The Last Station', ARRAY['fantasy','crime'], 2007, 104, 'A reluctant heir inherits a haunted crown.'),
('The Neon Summit', ARRAY['crime','sci-fi','family'], 2011, 95, 'A heist goes wrong in the first minute.'),
('The Neon Circuit', ARRAY['comedy','action','animation'], 2015, 45, 'Two strangers stumble into a scheme.'),
('The Midnight Empire', ARRAY['sci-fi'], 2014, 45, 'A crew finds a signal from the future.'),
('The Broken Machine', ARRAY['documentary','thriller'], 2024, 95, 'A true story told by the people who lived it.'),
('The Hidden River', ARRAY['thriller','horror','sci-fi'], 2005, 128, 'A detective races a deadline.'),
('The Iron River', ARRAY['action','sci-fi'], 2017, 117, 'A retired agent takes one last job.'),
('The Last Machine', ARRAY['romance'], 2024, 141, 'Two people keep missing each other.'),
('The Silent River', ARRAY['crime','fantasy'], 2013, 45, 'A heist goes wrong in the first minute.'),
('The Hidden Archive', ARRAY['comedy'], 2011, 104, 'Two strangers stumble into a scheme.'),
('The Crimson Kingdom', ARRAY['thriller','action'], 2011, 128, 'A detective races a deadline.'),
('The Iron Island', ARRAY['family','romance','comedy'], 2012, 22, 'Siblings spend one strange summer together.');
