-- Richer, distinct descriptions (step 5): semantic search needs text worth
-- understanding. Titles are matched by name, which is unique in the seed.
UPDATE titles SET description = 'A grieving widow moves into an old farmhouse where the ghosts are more awkward than frightening, and learns to laugh again.', updated_at = now() WHERE name = 'The Distant Circuit';
UPDATE titles SET description = 'Three adult sisters reunite for their father''s wedding and bicker their way toward forgiving each other.', updated_at = now() WHERE name = 'The Glass Signal';
UPDATE titles SET description = 'A crew of burglars plans to rob a museum vault, but their getaway driver never shows up.', updated_at = now() WHERE name = 'The Last Archive';
UPDATE titles SET description = 'Two children spend a night in their grandmother''s creaking mansion and discover something living in the walls.', updated_at = now() WHERE name = 'The Glass Frontier';
UPDATE titles SET description = 'A retired safecracker is pulled back for one final bank job by the nephew he raised.', updated_at = now() WHERE name = 'The Crimson Archive';
UPDATE titles SET description = 'A shy apprentice wizard must carry a cursed sword across enchanted mountains to save her kingdom.', updated_at = now() WHERE name = 'The Hollow Circuit';
UPDATE titles SET description = 'A florist and a ferry captain keep crossing paths on a tiny island and refuse to admit they are falling in love.', updated_at = now() WHERE name = 'The Hidden Island';
UPDATE titles SET description = 'A fishing village is terrorised by a masked killer while a hard-nosed smuggler fights to get her family out.', updated_at = now() WHERE name = 'The Northern Tide';
UPDATE titles SET description = 'Scientists and astronauts recall, in their own words, the decade they spent building a space station in orbit.', updated_at = now() WHERE name = 'The Glass Station';
UPDATE titles SET description = 'An animated band of raccoon thieves plots to steal the golden acorn from the richest squirrel in the forest.', updated_at = now() WHERE name = 'The Last Island';
UPDATE titles SET description = 'A clumsy postman accidentally delivers a love letter to the wrong town and chaos follows.', updated_at = now() WHERE name = 'The Wild Letter';
UPDATE titles SET description = 'Visitors to a remote abandoned hotel start vanishing one by one after midnight.', updated_at = now() WHERE name = 'The Quiet Empire';
UPDATE titles SET description = 'A cartoon dragon who is afraid of fire teams up with a talking teapot to rescue a silly prince.', updated_at = now() WHERE name = 'The Distant Machine';
UPDATE titles SET description = 'A family spends one summer on their grandparents'' apple farm and learns to work together.', updated_at = now() WHERE name = 'The Quiet Orchard';
UPDATE titles SET description = 'A hand-drawn story of a girl paddling down a great river to find her lost father.', updated_at = now() WHERE name = 'The Wild River';
UPDATE titles SET description = 'The real voyage of the first explorers who tried to settle a colony on Mars, told through their diaries.', updated_at = now() WHERE name = 'The Northern Frontier';
UPDATE titles SET description = 'An animated goldfish accidentally becomes the prime suspect in a city-wide conspiracy.', updated_at = now() WHERE name = 'The Burning River';
UPDATE titles SET description = 'A father and his two kids must escape a collapsing theme park during an earthquake.', updated_at = now() WHERE name = 'The Broken Empire';
UPDATE titles SET description = 'A night-shift nurse realises that a patient in her ward is a hitman waiting for his target.', updated_at = now() WHERE name = 'The Midnight Circuit';
UPDATE titles SET description = 'A reporter investigates legends of sea witches in a fog-bound port and finds that they are real.', updated_at = now() WHERE name = 'The Midnight Harbor';
UPDATE titles SET description = 'An accountant discovers his firm launders money for a cartel and has one night to get the evidence out.', updated_at = now() WHERE name = 'The Paper Machine';
UPDATE titles SET description = 'A mischievous grandpa and his grandkids race homemade rafts in a wild riverside contest full of stunts.', updated_at = now() WHERE name = 'The Paper River';
UPDATE titles SET description = 'The crew of a deep-space freighter wakes from hibernation to find their ship drifting far off course among unknown stars.', updated_at = now() WHERE name = 'The Crimson Tide';
UPDATE titles SET description = 'Two rival gardeners sabotage each other''s prize pumpkins at the village fair in a battle of pranks.', updated_at = now() WHERE name = 'The Hidden Garden';
UPDATE titles SET description = 'A young queen wields forbidden magic to protect her people and pays a painful price.', updated_at = now() WHERE name = 'The Paper Frontier';
UPDATE titles SET description = 'Survivors describe the true events behind a notorious haunting in a small northern town.', updated_at = now() WHERE name = 'The Northern River';
UPDATE titles SET description = 'A colourful cartoon about a little fox who dreams of flying with the geese.', updated_at = now() WHERE name = 'The Quiet Frontier';
UPDATE titles SET description = 'Passengers on a luxury cruise are trapped with a killer when the ship loses all power at sea.', updated_at = now() WHERE name = 'The Quiet Voyage';
UPDATE titles SET description = 'A detective investigating a murder in a snowbound town uncovers her own family''s buried crimes.', updated_at = now() WHERE name = 'The Frozen Echo';
UPDATE titles SET description = 'Hackers plan to drain a crypto exchange but one of them is an undercover cop.', updated_at = now() WHERE name = 'The Broken Code';
UPDATE titles SET description = 'Two climbers who were once lovers are stranded on a mountain with a stranger who is lying about everything.', updated_at = now() WHERE name = 'The Frozen Summit';
UPDATE titles SET description = 'A time-travelling soldier fights robots in a future city to stop a war before it starts.', updated_at = now() WHERE name = 'The Midnight Letter';
UPDATE titles SET description = 'A widowed father and his teenage son rebuild their relationship while restoring an old car.', updated_at = now() WHERE name = 'The Iron Echo';
UPDATE titles SET description = 'Siblings find a magic lantern that grants wishes in the attic and learn to be careful what they ask for.', updated_at = now() WHERE name = 'The Quiet Lantern';
UPDATE titles SET description = 'An android who has lost its memory wanders a ruined planet looking for the humans who built it.', updated_at = now() WHERE name = 'The Lost Machine';
UPDATE titles SET description = 'An animated space adventure about a small robot and an alien kitten exploring the galaxy together.', updated_at = now() WHERE name = 'The Quiet Tide';
UPDATE titles SET description = 'An ex-marine fights off a gang of mercenaries who seize the farm town where she grew up.', updated_at = now() WHERE name = 'The Lost Orchard';
UPDATE titles SET description = 'Two bumbling bodyguards must protect a pop star through a chaotic night of car chases and explosions.', updated_at = now() WHERE name = 'The Golden Empire';
UPDATE titles SET description = 'A disgraced politician receives anonymous threats and suspects someone in his own inner circle.', updated_at = now() WHERE name = 'The Last Kingdom';
UPDATE titles SET description = 'A woman''s new boyfriend seems perfect until she finds letters from his previous wives, all missing.', updated_at = now() WHERE name = 'The Broken Letter';
UPDATE titles SET description = 'Soldiers on a distant mining colony battle giant alien creatures burrowing up from below.', updated_at = now() WHERE name = 'The Silent Frontier';
UPDATE titles SET description = 'In a future city run by surveillance, a thief steals memories and sells them to the highest bidder.', updated_at = now() WHERE name = 'The Frozen Tide';
UPDATE titles SET description = 'An aspiring writer and a publisher fall for each other through years of letters across the world.', updated_at = now() WHERE name = 'The Paper Empire';
UPDATE titles SET description = 'A clever eleven-year-old helps her mum, a police officer, solve a string of neighbourhood burglaries.', updated_at = now() WHERE name = 'The Iron Circuit';
UPDATE titles SET description = 'A codebreaker receives a message that predicts assassinations before they happen.', updated_at = now() WHERE name = 'The Golden Letter';
UPDATE titles SET description = 'A small-town sheriff chases a gang of bank robbers across the desert.', updated_at = now() WHERE name = 'The Quiet Letter';
UPDATE titles SET description = 'A mild-mannered dentist is mistaken for a mob boss and has to play along to survive.', updated_at = now() WHERE name = 'The Iron Summit';
UPDATE titles SET description = 'Two detectives hunt a serial killer who leaves riddles at every crime scene.', updated_at = now() WHERE name = 'The Frozen Signal';
UPDATE titles SET description = 'A thief with the power to walk through shadows steals from a sorcerer who wants her dead.', updated_at = now() WHERE name = 'The Last Station';
UPDATE titles SET description = 'A kid and her robot sidekick catch a gang of thieves stealing inventions in a futuristic city.', updated_at = now() WHERE name = 'The Neon Summit';
UPDATE titles SET description = 'Cartoon superheroes with ridiculous powers try to save their city from a villain made of jelly.', updated_at = now() WHERE name = 'The Neon Circuit';
UPDATE titles SET description = 'An astronaut stranded alone on the Moon must find a way home before her oxygen runs out.', updated_at = now() WHERE name = 'The Midnight Empire';
UPDATE titles SET description = 'The true story of a whistleblower who exposed a global spy network and went into hiding.', updated_at = now() WHERE name = 'The Broken Machine';
UPDATE titles SET description = 'A research team in the Arctic thaws out an ancient organism that begins to take over their bodies.', updated_at = now() WHERE name = 'The Hidden River';
UPDATE titles SET description = 'A pilot leads the last human fighters against an alien invasion fleet above Earth.', updated_at = now() WHERE name = 'The Iron River';
UPDATE titles SET description = 'A widowed baker gets a second chance at love when a stranger orders the same cake every week.', updated_at = now() WHERE name = 'The Last Machine';
UPDATE titles SET description = 'A pickpocket in a magical city steals a cursed ring from the wrong man.', updated_at = now() WHERE name = 'The Silent River';
UPDATE titles SET description = 'A lazy office worker fakes being a genius and is promoted to run the company.', updated_at = now() WHERE name = 'The Hidden Archive';
UPDATE titles SET description = 'A bodyguard must get a witness across a hostile city in twelve hours while assassins close in.', updated_at = now() WHERE name = 'The Crimson Kingdom';
UPDATE titles SET description = 'Cousins spend a summer at a seaside resort, where a teenage romance and a lost dog turn the holiday upside down.', updated_at = now() WHERE name = 'The Iron Island';
