apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stream-hub
resources:
  - namespace.yaml
  - config.yaml
  - gateway.yaml
  - catalog-service.yaml
  - user-service.yaml
  - playback-service.yaml
  - history-service.yaml
  - home-service.yaml
  - recs-service.yaml
  - assistant-service.yaml
  - autoscaling.yaml
